universe                = vanilla
notification            = never
executable              = /lbne/u/mvicenzi/ml-dune-model/gridutils/diagnostics/testjob.sh
arguments               = /lbne/u/mvicenzi/ml-dune-model /gpfs01/lbne/users/fm/mvicenzi/uvenv /gpfs01/lbne/users/fm/mvicenzi/CONDOR_OUT tests/test_attention_pe.py
environment             = "CLUSTER_ID=$(ClusterId) JOB_ID=$(ProcId)"
output                  = /gpfs01/lbne/users/fm/mvicenzi/CONDOR_OUT/tests/$(ClusterId).$(ProcId).out
error                   = /gpfs01/lbne/users/fm/mvicenzi/CONDOR_OUT/tests/$(ClusterId).$(ProcId).err
log                     = /gpfs01/lbne/users/fm/mvicenzi/CONDOR_OUT/tests/$(ClusterId).$(ProcId).log
getenv                  = False
request_memory          = 16000
request_cpus            = 1
request_gpus            = 1
Requirements            = (GPUs_DeviceName == "NVIDIA L40S") && (GPUs_Capability == 8.9)
should_transfer_files   = NO
queue
